#spring:
#  data:
#    mongodb:
#      host: auth-mongodb
#      username: user
#      password: ${MONGODB_PASSWORD}
#      database: piggymetrics
#      port: 27017
#
#logging:
#  level:
#    org.springframework.security: INFO
#
#server:
#  port: 5000
#  context-path: /uaa
