version: '2'
services:
  registry:
    image: sqshq/piggymetrics-registry
    restart: always
    logging:
      options:
        max-size: "30m"
        max-file: "10"

  gateway:
    image: sqshq/piggymetrics-gateway
    restart: always
    logging:
      options:
        max-size: "30m"
        max-file: "10"

  account-service:
    image: sqshq/piggymetrics-account-service
    restart: always
    logging:
      options:
        max-size: "30m"
        max-file: "10"

  account-mongodb:
    build: mongodb
    image: sqshq/piggymetrics-account-mongodb
    restart: always
    logging:
      options:
        max-size: "30m"
        max-file: "10"
    environment:
      - INIT_DUMP=account_dump.js

#для дев версии запускать docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d
#      запомнить это для прод версии
#      а потом в дев версии прописать намертво дев-пароли