version: '2'
services:
  config:
    environment:
      CONFIG_SERVICE_PASSWORD:
    image: sqshq/piggymetrics-config
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  registry:
    environment:
      CONFIG_SERVICE_PASSWORD:
    image: sqshq/piggymetrics-registry
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  gateway:
    environment:
      CONFIG_SERVICE_PASSWORD:
    image: sqshq/piggymetrics-gateway
    restart: always
    ports:
      - 80:4000
    logging:
      options:
        max-size: "10m"
        max-file: "10"


  auth-service:
    environment:
      CONFIG_SERVICE_PASSWORD:
      NOTIFICATION_SERVICE_PASSWORD:
      STATISTICS_SERVICE_PASSWORD:
      ACCOUNT_SERVICE_PASSWORD:
      MONGODB_PASSWORD:
    image: sqshq/piggymetrics-auth-service
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  auth-mongodb:
    environment:
      MONGODB_PASSWORD:
    build: mongodb
    image: sqshq/piggymetrics-auth-mongodb
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"


  account-service:
    environment:
      CONFIG_SERVICE_PASSWORD:
      ACCOUNT_SERVICE_PASSWORD:
      MONGODB_PASSWORD:
    image: sqshq/piggymetrics-account-service
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  account-mongodb:
    environment:
      INIT_DUMP: account-service-dump.js
      MONGODB_PASSWORD:
    build: mongodb
    image: sqshq/piggymetrics-account-mongodb
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"


  statistics-service:
    environment:
      CONFIG_SERVICE_PASSWORD:
      STATISTICS_SERVICE_PASSWORD:
      MONGODB_PASSWORD:
    image: sqshq/piggymetrics-statistics-mongodb
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  statistics-mongodb:
    build: mongodb
    environment:
      MONGODB_PASSWORD:
    image: sqshq/piggymetrics-statistics-mongodb
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"


  notification-service:
    environment:
      CONFIG_SERVICE_PASSWORD:
      STATISTICS_SERVICE_PASSWORD:
      MONGODB_PASSWORD:
    image: sqshq/piggymetrics-notification-service
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

#  notification-mongodb:
#    build: mongodb
#    image: sqshq/piggymetrics-statistics-mongodb
#    restart: always
#    environment:
#      MONGODB_PASSWORD:
#    logging:
#      options:
#        max-size: "10m"
#        max-file: "10"
