security:
  oauth2:
    client:
      clientId: account-service
      clientSecret: password
      accessTokenUri: http://localhost:8888/uaa/oauth/token
      grant-type: client_credentials
      scope: server
    resource:
      user-info-uri: http://localhost:8888/uaa/user

spring:
  data:
    mongodb:
      host: localhost #account-mongodb
#      username: user
#      password: password #${MONGODB_PASSWORD}
      database: piggymetrics
      port: 27017

logging:
  level:
    org.springframework.security: DEBUG

server:
  context-path: /accounts
  port: 9999
